// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzHtFS8rbwjoHyaI82PmRPAPdClHmqrqg',
    appId: '1:517699410012:web:1a7deb536da401af67ee99',
    messagingSenderId: '517699410012',
    projectId: 'chat-app-85d35',
    authDomain: 'chat-app-85d35.firebaseapp.com',
    storageBucket: 'chat-app-85d35.firebasestorage.app',
    measurementId: 'G-XYHC3CLC7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwhasv_zjTwESJfCKMBMZWw56KkOuqVnY',
    appId: '1:517699410012:android:a31a052cff3fc5ab67ee99',
    messagingSenderId: '517699410012',
    projectId: 'chat-app-85d35',
    storageBucket: 'chat-app-85d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdGaa6F0fcpm_1DjKGsnGpKMT6V2iGms',
    appId: '1:517699410012:ios:dde45bebe90a072367ee99',
    messagingSenderId: '517699410012',
    projectId: 'chat-app-85d35',
    storageBucket: 'chat-app-85d35.firebasestorage.app',
    iosBundleId: 'com.example.firebaselearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcdGaa6F0fcpm_1DjKGsnGpKMT6V2iGms',
    appId: '1:517699410012:ios:dde45bebe90a072367ee99',
    messagingSenderId: '517699410012',
    projectId: 'chat-app-85d35',
    storageBucket: 'chat-app-85d35.firebasestorage.app',
    iosBundleId: 'com.example.firebaselearning',
  );

}